[workspace]
members = ["crates/cell-sheet-core", "crates/cell-sheet-tui"]
resolver = "2"

[workspace.dependencies]
cell-sheet-core = { path = "crates/cell-sheet-core", version = "0.5.1" }

[workspace.package]
version = "0.5.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/garritfra/cell"
homepage = "https://github.com/garritfra/cell"
authors = ["Garrit Franke"]
